# Generated by Django 5.2.17 on 2026-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('height_cm', models.FloatField(help_text='Height in centimeters')),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly Active (1–3 days/week)'), ('moderate', 'Moderately Active (3–5 days/week)'), ('active', 'Very Active (6–7 days/week)'), ('very_active', 'Extra Active (hard exercise / physical job)')], max_length=20)),
                ('fitness_goal', models.CharField(choices=[('weight_gain', 'Weight Gain'), ('weight_loss', 'Weight Loss'), ('maintain', 'Maintain Weight')], max_length=20)),
                ('dietary_preference', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian')], max_length=20)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=30)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('daily_calories', models.FloatField(blank=True, null=True)),
                ('calorie_target', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
