# Generated by Django 5.2.17 on 2026-08-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('serving_size', models.CharField(max_length=80)),
                ('calories', models.FloatField(help_text='Calories per serving')),
                ('protein', models.FloatField(help_text='Protein (g) per serving')),
                ('carbohydrates', models.FloatField(help_text='Carbohydrates (g) per serving')),
                ('fat', models.FloatField(help_text='Fat (g) per serving')),
                ('fiber', models.FloatField(help_text='Fiber (g) per serving')),
                ('dietary_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('non_vegetarian', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('quantity', models.FloatField(help_text='Number of servings')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dietapp.food')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='dietapp.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
