# Generated by Django 5.2.17 on 2026-08-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0002_food_foodlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('glasses', models.PositiveIntegerField(default=0, help_text='Number of 250ml glasses')),
                ('target_glasses', models.PositiveIntegerField(default=8, help_text='Target glasses per day')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='dietapp.userprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
