# Generated by Django 5.2.17 on 2026-08-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0003_waterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_dairy_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='is_gluten_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='is_nut_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='is_vrat_friendly',
            field=models.BooleanField(default=False, help_text='Allowed during Upvas/Vrat'),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium_mg',
            field=models.FloatField(default=50.0, help_text='Sodium (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar_g',
            field=models.FloatField(default=2.0, help_text='Sugar (g)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, help_text='e.g. gluten_free, dairy_free, nut_free', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fasting_protocol',
            field=models.CharField(choices=[('none', 'No Fasting Schedule'), ('16_8', '16:8 Protocol (16h Fast / 8h Eating Window)'), ('14_10', '14:10 Protocol (14h Fast / 10h Eating Window)'), ('12_12', '12:12 Circadian Fasting')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_condition',
            field=models.CharField(choices=[('none', 'General / Healthy Maintenance'), ('diabetes', 'Diabetes / Blood Sugar Control (Low GI, High Fiber)'), ('hypertension', 'Hypertension / Heart Health (Low Sodium, High Potassium)'), ('pcos', 'PCOS / Thyroid Support (Anti-inflammatory, High Protein)'), ('gerd', 'GERD / Digestive Sensitivity (Mild, Low Acid)')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight_kg',
            field=models.FloatField(blank=True, help_text='Target goal weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_indian_bmi',
            field=models.BooleanField(default=True, help_text='Use Indian ICMR standards (overweight >= 23, obese >= 25)'),
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_name', models.CharField(max_length=80)),
                ('duration_mins', models.PositiveIntegerField(default=30)),
                ('calories_burned', models.FloatField(default=150.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='dietapp.userprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FastingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('target_hours', models.PositiveIntegerField(default=16)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasting_logs', to='dietapp.userprofile')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='dietapp.userprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
